require('./preloader/preloader');
require('./burger/burger');
require('./OwlCarousel2-2.3.4/dist/owl.carousel.min');
require('./header/header');
require('./section-first-screen/section-first-screen');
require('./section-main/section-main');
require('./Lightbox/js/lc_lightbox.lite.min');
require('./section-works/section-works');
require('./section-contacts/section-contacts');